# This file is auto-generated by tools/create_zone_pm.pl
# Olson Version: 2006n
# DO NOT EDIT!
package DateTime::TimeZone::FromCountry::Zone;
use strict;
use base qw( Exporter );
our @EXPORT_OK = qw($Map);

our $Map = {
          'GL' => [
                    'America/Godthab',
                    'America/Danmarkshavn',
                    'America/Scoresbysund',
                    'America/Thule'
                  ],
          'DJ' => [
                    'Africa/Djibouti'
                  ],
          'JM' => [
                    'America/Jamaica'
                  ],
          'PG' => [
                    'Pacific/Port_Moresby'
                  ],
          'AT' => [
                    'Europe/Vienna'
                  ],
          'KI' => [
                    'Pacific/Tarawa',
                    'Pacific/Enderbury',
                    'Pacific/Kiritimati'
                  ],
          'SZ' => [
                    'Africa/Mbabane'
                  ],
          'YT' => [
                    'Indian/Mayotte'
                  ],
          'BN' => [
                    'Asia/Brunei'
                  ],
          'ZM' => [
                    'Africa/Lusaka'
                  ],
          'CD' => [
                    'Africa/Kinshasa',
                    'Africa/Lubumbashi'
                  ],
          'BW' => [
                    'Africa/Gaborone'
                  ],
          'AO' => [
                    'Africa/Luanda'
                  ],
          'ZW' => [
                    'Africa/Harare'
                  ],
          'VC' => [
                    'America/St_Vincent'
                  ],
          'PR' => [
                    'America/Puerto_Rico'
                  ],
          'JP' => [
                    'Asia/Tokyo'
                  ],
          'NA' => [
                    'Africa/Windhoek'
                  ],
          'SH' => [
                    'Atlantic/St_Helena'
                  ],
          'TJ' => [
                    'Asia/Dushanbe'
                  ],
          'LC' => [
                    'America/St_Lucia'
                  ],
          'MA' => [
                    'Africa/Casablanca'
                  ],
          'VU' => [
                    'Pacific/Efate'
                  ],
          'SV' => [
                    'America/El_Salvador'
                  ],
          'MT' => [
                    'Europe/Malta'
                  ],
          'MN' => [
                    'Asia/Ulaanbaatar',
                    'Asia/Hovd',
                    'Asia/Choibalsan'
                  ],
          'MP' => [
                    'Pacific/Saipan'
                  ],
          'IT' => [
                    'Europe/Rome'
                  ],
          'RE' => [
                    'Indian/Reunion'
                  ],
          'WS' => [
                    'Pacific/Apia'
                  ],
          'FR' => [
                    'Europe/Paris'
                  ],
          'EG' => [
                    'Africa/Cairo'
                  ],
          'UZ' => [
                    'Asia/Samarkand',
                    'Asia/Tashkent'
                  ],
          'PW' => [
                    'Pacific/Palau'
                  ],
          'TK' => [
                    'Pacific/Fakaofo'
                  ],
          'LR' => [
                    'Africa/Monrovia'
                  ],
          'RW' => [
                    'Africa/Kigali'
                  ],
          'UM' => [
                    'Pacific/Johnston',
                    'Pacific/Midway',
                    'Pacific/Wake'
                  ],
          'TN' => [
                    'Africa/Tunis'
                  ],
          'BE' => [
                    'Europe/Brussels'
                  ],
          'EE' => [
                    'Europe/Tallinn'
                  ],
          'CK' => [
                    'Pacific/Rarotonga'
                  ],
          'BY' => [
                    'Europe/Minsk'
                  ],
          'SA' => [
                    'Asia/Riyadh'
                  ],
          'NO' => [
                    'Europe/Oslo'
                  ],
          'LS' => [
                    'Africa/Maseru'
                  ],
          'KR' => [
                    'Asia/Seoul'
                  ],
          'ZA' => [
                    'Africa/Johannesburg'
                  ],
          'PT' => [
                    'Europe/Lisbon',
                    'Atlantic/Madeira',
                    'Atlantic/Azores'
                  ],
          'BF' => [
                    'Africa/Ouagadougou'
                  ],
          'CA' => [
                    'America/St_Johns',
                    'America/Halifax',
                    'America/Glace_Bay',
                    'America/Moncton',
                    'America/Goose_Bay',
                    'America/Blanc-Sablon',
                    'America/Montreal',
                    'America/Toronto',
                    'America/Nipigon',
                    'America/Thunder_Bay',
                    'America/Pangnirtung',
                    'America/Iqaluit',
                    'America/Atikokan',
                    'America/Rankin_Inlet',
                    'America/Winnipeg',
                    'America/Rainy_River',
                    'America/Cambridge_Bay',
                    'America/Regina',
                    'America/Swift_Current',
                    'America/Edmonton',
                    'America/Yellowknife',
                    'America/Inuvik',
                    'America/Dawson_Creek',
                    'America/Vancouver',
                    'America/Whitehorse',
                    'America/Dawson'
                  ],
          'AM' => [
                    'Asia/Yerevan'
                  ],
          'CM' => [
                    'Africa/Douala'
                  ],
          'SR' => [
                    'America/Paramaribo'
                  ],
          'MG' => [
                    'Indian/Antananarivo'
                  ],
          'NP' => [
                    'Asia/Katmandu'
                  ],
          'BT' => [
                    'Asia/Thimphu'
                  ],
          'PL' => [
                    'Europe/Warsaw'
                  ],
          'TM' => [
                    'Asia/Ashgabat'
                  ],
          'GA' => [
                    'Africa/Libreville'
                  ],
          'CF' => [
                    'Africa/Bangui'
                  ],
          'BA' => [
                    'Europe/Sarajevo'
                  ],
          'AE' => [
                    'Asia/Dubai'
                  ],
          'TH' => [
                    'Asia/Bangkok'
                  ],
          'KY' => [
                    'America/Cayman'
                  ],
          'LA' => [
                    'Asia/Vientiane'
                  ],
          'PH' => [
                    'Asia/Manila'
                  ],
          'CC' => [
                    'Indian/Cocos'
                  ],
          'NI' => [
                    'America/Managua'
                  ],
          'TF' => [
                    'Indian/Kerguelen'
                  ],
          'NC' => [
                    'Pacific/Noumea'
                  ],
          'GU' => [
                    'Pacific/Guam'
                  ],
          'KZ' => [
                    'Asia/Almaty',
                    'Asia/Qyzylorda',
                    'Asia/Aqtobe',
                    'Asia/Aqtau',
                    'Asia/Oral'
                  ],
          'SJ' => [
                    'Arctic/Longyearbyen',
                    'Atlantic/Jan_Mayen'
                  ],
          'MM' => [
                    'Asia/Rangoon'
                  ],
          'NR' => [
                    'Pacific/Nauru'
                  ],
          'NE' => [
                    'Africa/Niamey'
                  ],
          'DM' => [
                    'America/Dominica'
                  ],
          'TO' => [
                    'Pacific/Tongatapu'
                  ],
          'MR' => [
                    'Africa/Nouakchott'
                  ],
          'AD' => [
                    'Europe/Andorra'
                  ],
          'SE' => [
                    'Europe/Stockholm'
                  ],
          'AZ' => [
                    'Asia/Baku'
                  ],
          'AF' => [
                    'Asia/Kabul'
                  ],
          'NG' => [
                    'Africa/Lagos'
                  ],
          'GS' => [
                    'Atlantic/South_Georgia'
                  ],
          'KE' => [
                    'Africa/Nairobi'
                  ],
          'BJ' => [
                    'Africa/Porto-Novo'
                  ],
          'ME' => [
                    'Europe/Podgorica'
                  ],
          'OM' => [
                    'Asia/Muscat'
                  ],
          'AX' => [
                    'Europe/Mariehamn'
                  ],
          'VN' => [
                    'Asia/Saigon'
                  ],
          'VG' => [
                    'America/Tortola'
                  ],
          'YE' => [
                    'Asia/Aden'
                  ],
          'CI' => [
                    'Africa/Abidjan'
                  ],
          'DZ' => [
                    'Africa/Algiers'
                  ],
          'LK' => [
                    'Asia/Colombo'
                  ],
          'ID' => [
                    'Asia/Jakarta',
                    'Asia/Pontianak',
                    'Asia/Makassar',
                    'Asia/Jayapura'
                  ],
          'FM' => [
                    'Pacific/Truk',
                    'Pacific/Ponape',
                    'Pacific/Kosrae'
                  ],
          'GE' => [
                    'Asia/Tbilisi'
                  ],
          'GM' => [
                    'Africa/Banjul'
                  ],
          'CX' => [
                    'Indian/Christmas'
                  ],
          'LV' => [
                    'Europe/Riga'
                  ],
          'RU' => [
                    'Europe/Kaliningrad',
                    'Europe/Moscow',
                    'Europe/Volgograd',
                    'Europe/Samara',
                    'Asia/Yekaterinburg',
                    'Asia/Omsk',
                    'Asia/Novosibirsk',
                    'Asia/Krasnoyarsk',
                    'Asia/Irkutsk',
                    'Asia/Yakutsk',
                    'Asia/Vladivostok',
                    'Asia/Sakhalin',
                    'Asia/Magadan',
                    'Asia/Kamchatka',
                    'Asia/Anadyr'
                  ],
          'LB' => [
                    'Asia/Beirut'
                  ],
          'FK' => [
                    'Atlantic/Stanley'
                  ],
          'FI' => [
                    'Europe/Helsinki'
                  ],
          'DE' => [
                    'Europe/Berlin'
                  ],
          'MV' => [
                    'Indian/Maldives'
                  ],
          'LU' => [
                    'Europe/Luxembourg'
                  ],
          'VE' => [
                    'America/Caracas'
                  ],
          'PN' => [
                    'Pacific/Pitcairn'
                  ],
          'BH' => [
                    'Asia/Bahrain'
                  ],
          'GI' => [
                    'Europe/Gibraltar'
                  ],
          'WF' => [
                    'Pacific/Wallis'
                  ],
          'RO' => [
                    'Europe/Bucharest'
                  ],
          'VI' => [
                    'America/St_Thomas'
                  ],
          'TV' => [
                    'Pacific/Funafuti'
                  ],
          'IN' => [
                    'Asia/Calcutta'
                  ],
          'GP' => [
                    'America/Guadeloupe'
                  ],
          'AR' => [
                    'America/Argentina/Buenos_Aires',
                    'America/Argentina/Cordoba',
                    'America/Argentina/Jujuy',
                    'America/Argentina/Tucuman',
                    'America/Argentina/Catamarca',
                    'America/Argentina/La_Rioja',
                    'America/Argentina/San_Juan',
                    'America/Argentina/Mendoza',
                    'America/Argentina/Rio_Gallegos',
                    'America/Argentina/Ushuaia'
                  ],
          'SN' => [
                    'Africa/Dakar'
                  ],
          'MX' => [
                    'America/Mexico_City',
                    'America/Cancun',
                    'America/Merida',
                    'America/Monterrey',
                    'America/Mazatlan',
                    'America/Chihuahua',
                    'America/Hermosillo',
                    'America/Tijuana'
                  ],
          'FO' => [
                    'Atlantic/Faeroe'
                  ],
          'AW' => [
                    'America/Aruba'
                  ],
          'MC' => [
                    'Europe/Monaco'
                  ],
          'HN' => [
                    'America/Tegucigalpa'
                  ],
          'BR' => [
                    'America/Noronha',
                    'America/Belem',
                    'America/Fortaleza',
                    'America/Recife',
                    'America/Araguaina',
                    'America/Maceio',
                    'America/Bahia',
                    'America/Sao_Paulo',
                    'America/Campo_Grande',
                    'America/Cuiaba',
                    'America/Porto_Velho',
                    'America/Boa_Vista',
                    'America/Manaus',
                    'America/Eirunepe',
                    'America/Rio_Branco'
                  ],
          'IL' => [
                    'Asia/Jerusalem'
                  ],
          'GG' => [
                    'Europe/Guernsey'
                  ],
          'SB' => [
                    'Pacific/Guadalcanal'
                  ],
          'PS' => [
                    'Asia/Gaza'
                  ],
          'NZ' => [
                    'Pacific/Auckland',
                    'Pacific/Chatham'
                  ],
          'HU' => [
                    'Europe/Budapest'
                  ],
          'DO' => [
                    'America/Santo_Domingo'
                  ],
          'UG' => [
                    'Africa/Kampala'
                  ],
          'KH' => [
                    'Asia/Phnom_Penh'
                  ],
          'TG' => [
                    'Africa/Lome'
                  ],
          'GB' => [
                    'Europe/London'
                  ],
          'BB' => [
                    'America/Barbados'
                  ],
          'JE' => [
                    'Europe/Jersey'
                  ],
          'HT' => [
                    'America/Port-au-Prince'
                  ],
          'DK' => [
                    'Europe/Copenhagen'
                  ],
          'PA' => [
                    'America/Panama'
                  ],
          'QA' => [
                    'Asia/Qatar'
                  ],
          'CV' => [
                    'Atlantic/Cape_Verde'
                  ],
          'GD' => [
                    'America/Grenada'
                  ],
          'MO' => [
                    'Asia/Macau'
                  ],
          'GF' => [
                    'America/Cayenne'
                  ],
          'KM' => [
                    'Indian/Comoro'
                  ],
          'HR' => [
                    'Europe/Zagreb'
                  ],
          'KW' => [
                    'Asia/Kuwait'
                  ],
          'TC' => [
                    'America/Grand_Turk'
                  ],
          'MQ' => [
                    'America/Martinique'
                  ],
          'CZ' => [
                    'Europe/Prague'
                  ],
          'MZ' => [
                    'Africa/Maputo'
                  ],
          'ES' => [
                    'Europe/Madrid',
                    'Africa/Ceuta',
                    'Atlantic/Canary'
                  ],
          'BO' => [
                    'America/La_Paz'
                  ],
          'ST' => [
                    'Africa/Sao_Tome'
                  ],
          'AU' => [
                    'Australia/Lord_Howe',
                    'Australia/Hobart',
                    'Australia/Currie',
                    'Australia/Melbourne',
                    'Australia/Sydney',
                    'Australia/Broken_Hill',
                    'Australia/Brisbane',
                    'Australia/Lindeman',
                    'Australia/Adelaide',
                    'Australia/Darwin',
                    'Australia/Perth'
                  ],
          'AL' => [
                    'Europe/Tirane'
                  ],
          'IR' => [
                    'Asia/Tehran'
                  ],
          'CG' => [
                    'Africa/Brazzaville'
                  ],
          'TR' => [
                    'Europe/Istanbul'
                  ],
          'MD' => [
                    'Europe/Chisinau'
                  ],
          'BI' => [
                    'Africa/Bujumbura'
                  ],
          'GN' => [
                    'Africa/Conakry'
                  ],
          'GW' => [
                    'Africa/Bissau'
                  ],
          'MK' => [
                    'Europe/Skopje'
                  ],
          'GR' => [
                    'Europe/Athens'
                  ],
          'AG' => [
                    'America/Antigua'
                  ],
          'SI' => [
                    'Europe/Ljubljana'
                  ],
          'CO' => [
                    'America/Bogota'
                  ],
          'AI' => [
                    'America/Anguilla'
                  ],
          'AQ' => [
                    'Antarctica/McMurdo',
                    'Antarctica/South_Pole',
                    'Antarctica/Rothera',
                    'Antarctica/Palmer',
                    'Antarctica/Mawson',
                    'Antarctica/Davis',
                    'Antarctica/Casey',
                    'Antarctica/Vostok',
                    'Antarctica/DumontDUrville',
                    'Antarctica/Syowa'
                  ],
          'AN' => [
                    'America/Curacao'
                  ],
          'JO' => [
                    'Asia/Amman'
                  ],
          'SM' => [
                    'Europe/San_Marino'
                  ],
          'UA' => [
                    'Europe/Kiev',
                    'Europe/Uzhgorod',
                    'Europe/Zaporozhye',
                    'Europe/Simferopol'
                  ],
          'CL' => [
                    'America/Santiago',
                    'Pacific/Easter'
                  ],
          'CU' => [
                    'America/Havana'
                  ],
          'EH' => [
                    'Africa/El_Aaiun'
                  ],
          'ML' => [
                    'Africa/Bamako'
                  ],
          'KN' => [
                    'America/St_Kitts'
                  ],
          'SC' => [
                    'Indian/Mahe'
                  ],
          'ET' => [
                    'Africa/Addis_Ababa'
                  ],
          'IS' => [
                    'Atlantic/Reykjavik'
                  ],
          'NL' => [
                    'Europe/Amsterdam'
                  ],
          'MS' => [
                    'America/Montserrat'
                  ],
          'EC' => [
                    'America/Guayaquil',
                    'Pacific/Galapagos'
                  ],
          'HK' => [
                    'Asia/Hong_Kong'
                  ],
          'MY' => [
                    'Asia/Kuala_Lumpur',
                    'Asia/Kuching'
                  ],
          'CR' => [
                    'America/Costa_Rica'
                  ],
          'VA' => [
                    'Europe/Vatican'
                  ],
          'IO' => [
                    'Indian/Chagos'
                  ],
          'SD' => [
                    'Africa/Khartoum'
                  ],
          'RS' => [
                    'Europe/Belgrade'
                  ],
          'CN' => [
                    'Asia/Shanghai',
                    'Asia/Harbin',
                    'Asia/Chongqing',
                    'Asia/Urumqi',
                    'Asia/Kashgar'
                  ],
          'MH' => [
                    'Pacific/Majuro',
                    'Pacific/Kwajalein'
                  ],
          'BG' => [
                    'Europe/Sofia'
                  ],
          'UY' => [
                    'America/Montevideo'
                  ],
          'PY' => [
                    'America/Asuncion'
                  ],
          'BS' => [
                    'America/Nassau'
                  ],
          'TL' => [
                    'Asia/Dili'
                  ],
          'MU' => [
                    'Indian/Mauritius'
                  ],
          'CH' => [
                    'Europe/Zurich'
                  ],
          'LI' => [
                    'Europe/Vaduz'
                  ],
          'GH' => [
                    'Africa/Accra'
                  ],
          'KG' => [
                    'Asia/Bishkek'
                  ],
          'NU' => [
                    'Pacific/Niue'
                  ],
          'US' => [
                    'America/New_York',
                    'America/Detroit',
                    'America/Kentucky/Louisville',
                    'America/Kentucky/Monticello',
                    'America/Indiana/Indianapolis',
                    'America/Indiana/Marengo',
                    'America/Indiana/Knox',
                    'America/Indiana/Vevay',
                    'America/Chicago',
                    'America/Indiana/Vincennes',
                    'America/Indiana/Petersburg',
                    'America/Menominee',
                    'America/North_Dakota/Center',
                    'America/North_Dakota/New_Salem',
                    'America/Denver',
                    'America/Boise',
                    'America/Shiprock',
                    'America/Phoenix',
                    'America/Los_Angeles',
                    'America/Anchorage',
                    'America/Juneau',
                    'America/Yakutat',
                    'America/Nome',
                    'America/Adak',
                    'Pacific/Honolulu'
                  ],
          'PE' => [
                    'America/Lima'
                  ],
          'SL' => [
                    'Africa/Freetown'
                  ],
          'BZ' => [
                    'America/Belize'
                  ],
          'CY' => [
                    'Asia/Nicosia'
                  ],
          'FJ' => [
                    'Pacific/Fiji'
                  ],
          'IM' => [
                    'Europe/Isle_of_Man'
                  ],
          'IE' => [
                    'Europe/Dublin'
                  ],
          'TW' => [
                    'Asia/Taipei'
                  ],
          'KP' => [
                    'Asia/Pyongyang'
                  ],
          'PF' => [
                    'Pacific/Tahiti',
                    'Pacific/Marquesas',
                    'Pacific/Gambier'
                  ],
          'ER' => [
                    'Africa/Asmera'
                  ],
          'IQ' => [
                    'Asia/Baghdad'
                  ],
          'AS' => [
                    'Pacific/Pago_Pago'
                  ],
          'TZ' => [
                    'Africa/Dar_es_Salaam'
                  ],
          'MW' => [
                    'Africa/Blantyre'
                  ],
          'LY' => [
                    'Africa/Tripoli'
                  ],
          'GT' => [
                    'America/Guatemala'
                  ],
          'GY' => [
                    'America/Guyana'
                  ],
          'BM' => [
                    'Atlantic/Bermuda'
                  ],
          'PK' => [
                    'Asia/Karachi'
                  ],
          'GQ' => [
                    'Africa/Malabo'
                  ],
          'LT' => [
                    'Europe/Vilnius'
                  ],
          'SG' => [
                    'Asia/Singapore'
                  ],
          'PM' => [
                    'America/Miquelon'
                  ],
          'TT' => [
                    'America/Port_of_Spain'
                  ],
          'NF' => [
                    'Pacific/Norfolk'
                  ],
          'TD' => [
                    'Africa/Ndjamena'
                  ],
          'SO' => [
                    'Africa/Mogadishu'
                  ],
          'SY' => [
                    'Asia/Damascus'
                  ],
          'SK' => [
                    'Europe/Bratislava'
                  ],
          'BD' => [
                    'Asia/Dhaka'
                  ]
        };


1;
