#!/usr/bin/env perl
use strict;
use warnings;
use Net::Rendezvous;
use Pod::Usage;

my $proto = shift @ARGV || pod2usage(1);
my $res = Net::Rendezvous->new($proto);
$res->discover;

for my $entry ($res->entries) {
    printf "%s %s:%s\n", $entry->name, $entry->address, $entry->port;
}

__END__

=head1 NAME

bonjourfind - Find Bonjour entries

=head1 SYNOPSIS

  bonjourfind [protocol]

=cut
