#!/usr/bin/env perl
use strict;
use YAML;

my @deps = grep { $_ ne 'perl' } keys %{ YAML::LoadFile("META.yml")->{requires} };
if ($ARGV[0] && $ARGV[0] eq '-i') {
    system "cpan", "-i", @deps;
} else {
    print join "\n", @deps, "";
}

