#!/usr/bin/osascript
on run argv
  set VPNServiceName to item 1 of argv

  tell application "System Events"
    tell current location of network preferences
      set VPNservice to service VPNServiceName
      set isConnected to connected of current configuration of VPNservice
      if isConnected then
        disconnect VPNservice
      else
        connect VPNservice
      end if
    end tell
  end tell
end run
