#!/usr/bin/env perl
use strict;
use warnings;
use DateTime;
use DateTime::TimeZone;
use Term::ANSIColor;

my @tz = (
    'Pacific/Honolulu',
    [ 'America/Los_Angeles' ],
    'America/Chicago',
    'America/New_York',
    'UTC',
    'Europe/London',
    'Asia/Taipei',
    [ 'Asia/Tokyo' ],
    'Australia/Sydney',
);

my $dt = DateTime->now;
for my $tz (@tz) {
    my $color;
    if (ref $tz) {
        $tz = $tz->[0];
        $color = 1;
    }
    $dt->set_time_zone($tz);
    print color 'yellow' if $color;

    my $offset = $dt->time_zone->offset_for_datetime($dt);
    print $dt->strftime("%Y/%m/%d (%a) %H:%M:%S "),
        $dt->time_zone->name,
        " (", $dt->time_zone->offset_as_string($offset),
        ($dt->is_dst ? '*' : ''),
        ")\n";
    print color 'reset' if $color;
}
